### ISSUE TITLE
Provide the ability for the form layout to set context variables (non private). 

### ISSUE THREAD

**Issue by drushbrook** [watson-virtual-agents/chat-widget#102]
Maybe I'm completely wrong with my understanding of the form layout and store object but AFAIK the form layout is really useful but limited because we can't set context variables back with it i.e. non PII content. 

I know that I could create my own custom version of it but it might be better if we create a parameter called type on the store object.

**Comment by ethanwinters** [comment]
Everything is added to IBMChat.profile on submit and you can access any content from there. Can you provide a more specific example of what you are trying to accomplish?

**Comment by drushbrook** [comment]
IBMChat.profile is only accessible on the chat-widget side and not WCS
right?
If not then can you tell me how I can access it?
If so I could write a function to expose the elements in IBMChat.profile
that I want back on context to WCS or better still look at this enhancement
request.

I want a method of requesting a structured information and putting them
back in context using the validation and rendering of the form layout.

A really bad example using the name example you have in the dialog contract.

{
    "output": {
        "text": "Hello $fname |&lname|"
    }
}

I have a form requesting both the First name (fname) and Last Name (lname)
and it stores the lname privately but the fname in context.

A better example is a post chat survey.
Rather than asking question by question - I want to ask a group of
questions using the form layout.
The responses to some of the questions I ask will be private and stored but
other's will need to direct the flow in WCS to the next questions that get
asked.

**Comment by ethanwinters** [comment]
Ok, I follow now. The round-about way of getting the data you want back on the server would be to have an action that the widget subscribes to and then send the appropriate profile data back to the server with sendSilently after the form submission. 

So... show form layout -> on success then send action:gatherContextVariables -> return the variables from the profile you want to save on the server side.

The idea of a form that picks out what data should be stored client side and which parts can be sent back to the server is interesting and is something I will put in our backlog for consideration. I'll put any updates on that happening here.

**Comment by drushbrook** [comment]
Thanks

**Comment by drushbrook** [comment]
Hey, This was closed without an update.   What was the outcome?

**Comment by ethanwinters** [comment]
We decided in the short term that we were going to keep things as is. As we look to other platforms, our use of forms is raising some interesting questions we need to answer.
