### ISSUE TITLE
Getting trouble to push the server to Bluemix

### ISSUE THREAD

**Issue by mkrudele** [watson-virtual-agents/chat-widget#113]
I'm having hard time pushing the simple chat-widget server to Bluemix. Anyone can help here?
This is the error I get from cloud foundry logs:  
```
npm ERR! argv "/home/vcap/app/vendor/node/bin/node" "/home/vcap/app/vendor/node/bin/npm" "run" "server:watch"
npm ERR! node v4.6.0
npm ERR! Linux 3.19.0-33-generic
at Module._compile (module.js:409:26)
module.js:327
at Module.load (module.js:343:32)
at Object.Module._extensions..js (module.js:416:10)
throw err;
at Module.require (module.js:353:17)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
Error: Cannot find module 'webpack'
at Object.<anonymous> (/home/vcap/app/dev-tools/server.js:15:17)
^
at require (internal/module.js:12:17)
at Function.Module._load (module.js:276:25)
at Function.Module._resolveFilename (module.js:325:15)
```

I added to package.json the script.start command = to script.watch command.  
I set bluemix env variable to NODE_ENV=development to have devDependencies installed (i.e. webpack), but it still not find webpack.  
Any help? Thanks in advance.

**Comment by ethanwinters** [comment]
This repo is not meant to act as a stand alone server to be deployed. The webpack dev server is specifically for local development. To use that chat widget on your own site, you can follow the instructions here: https://github.com/watson-virtual-agents/chat-widget/blob/master/docs/DOCS.md#quick-sample.

You can then deploy that static html file to bluemix on an ngnix server.

**Comment by mkrudele** [comment]
Thanks Ethan, appreciate your quick reply. I deployed a simple chat widget
embedded in a web page on bluemix following your suggestion.

Il 22/nov/2016 22:28, "Ethan Winters" <notifications@github.com> ha scritto:

This repo is not meant to act as a stand alone server to be deployed. The
webpack dev server is specifically for local development. To use that chat
widget on your own site, you can follow the instructions here:
https://github.com/watson-virtual-agents/chat-widget/
blob/master/docs/DOCS.md#quick-sample.

You can then deploy that static html file to bluemix on an ngnix server.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/watson-virtual-agents/chat-widget/issues/113#issuecomment-262370941>,
or mute the thread

**Comment by ethanwinters** [comment]
Great! We have holidays in the US this week, but feel free to reach out if you have any other questions.
