### ISSUE TITLE
Error in init() setting conf.playback to true 

### ISSUE THREAD

**Issue by ffbenedetti** [watson-virtual-agents/chat-widget#119]
Calling 

IBMChat.init({
    el: 'ibm_chat_root',
    baseURL: 'xxxxxx',
    botID: '100',
    XIBMClientID: 'fake',
    XIBMClientSecret: 'fake',
    playback: true
  })
throws the following error in the console:
resize.js:21 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined(…)(anonymous function) @ resize.js:21

This should be caused by the setting of the event handlers in bootstrap.js 

function registerEvents(tryIt, playback) {
....
  if (playback === true) { //TODO: remove if playback when Dashboard code is updated
    events.subscribe('send', eventHandlers.sendMock);
  } else {
    events.subscribe('resize-input', eventHandlers.resizeInput);
    events.subscribe('send', eventHandlers.send);

in the case of playback true the resize-input event handler is not set

**Comment by ethanwinters** [comment]
Thanks for the catch, will fix in next release.

We do recommend using the IBMChat.playback.init function (see src/playback/index.js) as we will be removing those undocumented APIs using playback as a config option on the base IBMChat.init function.

**Comment by ethanwinters** [comment]
Fixed in and will be included in next release: https://github.com/watson-virtual-agents/chat-widget/pull/121
