### ISSUE TITLE
Is this a current document and code?

### ISSUE THREAD

**Issue by aneeshsudhakaran** [watson-virtual-agents/chat-widget#258]
I cant see it working and find the api keys?

**Comment by ethanwinters** [comment]
Watson Virtual Agent has been sunset (https://console.bluemix.net/docs/services/virtual-agent/index.html#about) and its core feature set has been merged into Watson Assistant. Part of that merging of the products will include a new and improved version of a "chat widget", but that aspect is still in development. There is a *not supported* version of this chat widget in https://github.com/watson-virtual-agents/chat-widget/tree/wcs that was ported for former Watson Virtual Agent customers moving to Watson Assistant, but it is NOT recommended for new users of Watson Assistant.
