### ISSUE TITLE
IBMChat.init in src/index.html targets a div that doesn't exist

### ISSUE THREAD

**Issue by drushbrook** [watson-virtual-agents/chat-widget#60]
Last commit (9e6e0e1a5a27ba6ab4d140876b33af95302506d0) to src/index.html updated css and javascript to ibm_element but the div stayed as ibm_el.  This causes nothing to be displayed.

Fixed for me by updating line 28 to
`<div id="ibm_element"></div>`

**Comment by ethanwinters** [comment]
Thanks for the catch! Master updated.
