### ISSUE TITLE
Support for localization of terms

### ISSUE THREAD

**Issue by drushbrook** [watson-virtual-agents/chat-widget#79]
For example:
In 
https://github.com/watson-virtual-agents/chat-widget/blob/master/src/layouts/choose-location-type/templates/base.html#L3 it uses Zip Code which is the Postal Code synonym used primarily only in the United States and the Philippines.  

See http://www.grcdi.nl/gsb/summary_%20postal%20code%20synonyms.html

**Comment by ethanwinters** [comment]
Thanks! Internationalization of all kinds is on our roadmap, but probably won't be addressed in Q4.

**Comment by ethanwinters** [comment]
We now support language packs and internationalization
